---
- hosts: all
  become: yes
  user: centos
  roles:
    - common

- hosts: host1
  become: yes
  user: centos
  roles:
    - openssl-ca-generate

- hosts: all
  become: yes
  user: centos
  roles:
    - openssl-cachain-distribute

- hosts: host1
  become: yes
  user: centos
  roles:
    - openssl-ca-intermediate-generate

- hosts: all
  become: yes
  user: centos
  roles:
    - openssl-cachain-intermediate-distribute

- hosts: host1
  become: yes
  user: centos
  roles:
    - openssl-clients-generate

- hosts: all
  become: yes
  user: centos
  roles:
    - openssl-clients-distribute