---
- name: generate CA private key
  shell: openssl genrsa -aes256 -out private/ca.key.pem 4096 mode=400
  args:
    chdir: "{{ ca_certs_dir }}"

- name: create root CA cert
  shell: openssl req -config openssl.cnf \
      -key private/ca.key.pem \
      -new -x509 -days 7300 -sha256 -extensions v3_ca \
      -out certs/ca.cert.pem -passin pass:{{ ca_rootca_password }} -subj \"{{ ca_subject }}\"
  args:
    chdir: "{{ ca_certs_dir }}"